---
title: "specieslist"
author: "Ewout Knoester"
date: "15/11/2021"
output: html_document
---

```{r setup, include=FALSE}

rm(list=ls()) # Clear workspace
knitr::opts_knit$set(root.dir = '/tmp') #Set directory at current directory for all subsequent chunks
options(scipen = 50) # Have all numbers in non-scientific notation

library(plyr) # Join (vlookup)
library(tidyverse) # Data manipulation and plotting
library(readxl) # Import excel sheets
library(htmlTable) # Data table
library(ggthemes) # pretty plots

```

# Load & organize data
<!--
Data info:
  Data collected by 
-->

```{r}

# Load raw data
db.0raw <- read_excel("Fish surveys_DATABASE_04_Selection.xlsx", sheet = "SPECIES")

# Drop irrelevant columns
db.1clean <- db.0raw[-c(2, 5, 6, 9)]
db.1clean$Site <- as.factor(db.1clean$Site)


# FACULTATIVE CORALLIVORES
db.2Fac <- subset(db.1clean, Corallivore.F == "YES" & Corallivore.O == "NO" )

## Average per Species by Site
db.2Fac.sum <- db.2Fac  %>%  
  group_by(Species, Site) %>% 
  dplyr::summarise(Biomass.sum = sum(Biomass, na.rm = TRUE))

## Calculate biomass in kg/ha
db.2Fac.sum <- as.data.frame(append(db.2Fac.sum, list(Surveys = ""))) 

### Set varying number of Surveys per Site
db.2Fac.sum$Surveys <- ifelse(
  db.2Fac.sum$Site == 1, 11, ifelse(db.2Fac.sum$Site == 2, 13, ifelse(db.2Fac.sum$Site == 3, 15,
                           ifelse(db.2Fac.sum$Site == 4, 15, ifelse(db.2Fac.sum$Site == 5, 11, 12)))))

### Calculate Biomass (kg/ha)
db.2Fac.sum <- as.data.frame(append(db.2Fac.sum, list(Biomass.kgha = db.2Fac.sum$Biomass.sum / db.2Fac.sum$Surveys))) 

## Average Biomass of Facultative corallivores per Site
db.2Fac.avgSite <- db.2Fac.sum  %>%  
  group_by(Site) %>% 
  dplyr::summarise(Biomass = sum(Biomass.kgha, na.rm = TRUE))

## Sort by total biomass per Species 
### Average Biomass of Facultative corallivores per Species
db.2Fac.avgSpecies <- db.2Fac.sum  %>%  
  group_by(Species) %>% 
  dplyr::summarise(Biomass.tot = sum(Biomass.kgha, na.rm = TRUE))

### Create category Other, for those species having relatively few Bites
#### Express biomass in percentages
Total.Fac <- sum(db.2Fac.avgSpecies$Biomass.tot)
db.2Fac.avgSpecies <- as.data.frame(append(db.2Fac.avgSpecies, 
                      list(Biomass.pct = db.2Fac.avgSpecies$Biomass.tot / Total.Fac * 100)))

#### Join dataframes
db.2Fac.sum <- plyr::join(db.2Fac.sum, db.2Fac.avgSpecies, by = "Species")

#### Change Species names to category Other, when their total Bites contribute < 3%
db.2Fac.sum$Species <- ifelse(db.2Fac.sum$Biomass.pct < 3, "Other", as.character(db.2Fac.sum$Species))

#### Drop coluns
db.2Fac.sum <- db.2Fac.sum[-c(3, 4, 7)] 


# OBLIGATE CORALLIVORES
db.2Obl <- subset(db.1clean, Corallivore.O == "YES")

## Average per Species by Site
db.2Obl.sum <- db.2Obl  %>%  
  group_by(Species, Site) %>% 
  dplyr::summarise(Biomass.sum = sum(Biomass, na.rm = TRUE))

## Calculate biomass in kg/ha
db.2Obl.sum <- as.data.frame(append(db.2Obl.sum, list(Surveys = ""))) 

### Set varying number of Surveys per Site
db.2Obl.sum$Surveys <- ifelse(
  db.2Obl.sum$Site == 1, 11, ifelse(db.2Obl.sum$Site == 2, 13, ifelse(db.2Obl.sum$Site == 3, 15,
                           ifelse(db.2Obl.sum$Site == 4, 15, ifelse(db.2Obl.sum$Site == 5, 11, 12)))))

### Calculate Biomass (kg/ha)
db.2Obl.sum <- as.data.frame(append(db.2Obl.sum, list(Biomass.kgha = db.2Obl.sum$Biomass.sum / db.2Obl.sum$Surveys))) 

## Average Biomass of Facultative corallivores per Site
db.2Obl.avgSite <- db.2Obl.sum  %>%  
  group_by(Site) %>% 
  dplyr::summarise(Biomass = sum(Biomass.kgha, na.rm = TRUE))

## Sort by total biomass per Species 
### Average Biomass of Facultative corallivores per Species
db.2Obl.avgSpecies <- db.2Obl.sum  %>%  
  group_by(Species) %>% 
  dplyr::summarise(Biomass.tot = sum(Biomass.kgha, na.rm = TRUE))

### Create category Other, for those species having relatively few Bites
#### Express biomass in percentages
Total.Obl <- sum(db.2Obl.avgSpecies$Biomass.tot)
db.2Obl.avgSpecies <- as.data.frame(append(db.2Obl.avgSpecies, 
                      list(Biomass.pct = db.2Obl.avgSpecies$Biomass.tot / Total.Obl * 100)))

#### Join dataframes
db.2Obl.sum <- plyr::join(db.2Obl.sum, db.2Obl.avgSpecies, by = "Species")

#### Change Species names to category Other, when their total Bites contribute < 0.5% (none)
db.2Obl.sum$Species <- ifelse(db.2Obl.sum$Biomass.pct < 0.5, "Other", as.character(db.2Obl.sum$Species))

#### Drop coluns
db.2Obl.sum <- db.2Obl.sum[-c(3, 4, 7)] 


```

# Plotting
```{r plotting}

# Stacked bar Facultative corallivores
ggplot(db.2Fac.sum, aes(fill=Site, y=Biomass.kgha, x=reorder(Species, -Biomass.tot))) + 
    geom_bar(position="stack", stat="identity")+
    scale_fill_manual(values = c("#b3dcff", "#a1c6e5", "#ffd989", "#E5C37B", "#e06060", "#c95656"))+
    labs(y = expression(paste("Fish biomass (kg ", ha^-1,")")), x = "Species")+
    theme_economist()+
    theme(
      axis.title.x = element_text(color="black", vjust=-2, size = 12),
      axis.text.x=element_text(size=12, face = "bold", vjust=0.5, angle = -35, hjust=0),
      axis.title.y = element_text(color="black" , vjust=4, size = 12),
      axis.text.y=element_text(size=12, face = "bold", vjust=0.5)
      )
ggsave("Facultative corallivores.tiff", width = 23, height = 10, units = "cm", dpi=1200, compression = "lzw")

# Stacked bar Obligate corallivores
ggplot(db.2Obl.sum, aes(fill=Site, y=Biomass.kgha, x=reorder(Species, -Biomass.tot))) + 
    geom_bar(position="stack", stat="identity")+
    scale_fill_manual(values = c("#b3dcff", "#a1c6e5", "#ffd989", "#E5C37B", "#e06060", "#c95656"))+
    labs(y = expression(paste("Fish biomass (kg ", ha^-1,")")), x = "Species")+
    theme_economist()+
    theme(
      axis.title.x = element_text(color="black", vjust=-2, size = 12),
      axis.text.x=element_text(size=12, face = "bold", vjust=0.5, angle = -35, hjust=0),
      axis.title.y = element_text(color="black" , vjust=4, size = 12),
      axis.text.y=element_text(size=12, face = "bold", vjust=0.5),
      plot.margin = unit(c(0.5,3.5,0.5,0.5), "cm")
      )
ggsave("Obligate corallivores.tiff", width = 23, height = 10, units = "cm", dpi=1200, compression = "lzw")

```
